services:
  concert-reservation:
    container_name: concert-reservation
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROFILE: local-docker
    ports:
      - 8080:8080
    deploy:  
      resources:  
        limits:  
          cpus: '0.25'
          memory: '2G'