services:
  concert-reservation:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROFILE: local-docker
    networks:
      - hhplus

networks:
  hhplus:
    driver: bridge
    external: true