spring.application.name: concert-reservation

# Redis Config
spring.data.redis:
  host: localhost
  port: 6379
  default-cache-ttl: 10
  keyspace:
    waiting-token: "waitingQueueToken"
    active-token: "activeToken"
    reservation: "reservation"

# Async Config
spring.async.execution.pool:
  core-size: 4
  max-size: 20
  queue-capacity: 500

# Kafka Consumer/Producer Config
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

---
spring.config.activate.on-profile: test

spring.datasource:
  driver-class-name: org.h2.Driver

---
spring.config.activate.on-profile: query-test

spring.datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  username: root
  password: 1234
  url: jdbc:mariadb://localhost:3306/hpp_concert?characterEncoding=utf8