spring.application.name: concert-reservation


spring.data.redis:
  host: localhost
  port: 6379
  keyspace:
    waiting-token: "waitingQueueToken"
    active-token: "activeToken"
    reservation: "reservation"
